version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
      TZ: "Asia/Tokyo"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./git:/var/jenkins_home/git
